version: "3.7"

services:
  # MySQL
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/config/init/:/docker-entrypoint-initdb.d/
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "root"
      MYSQL_ROOT_PASSWORD: "root"
  
  # MongoDB
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data/:/data/db
      - "./mongodb/config/init/:/docker-entrypoint-initdb.d/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  # # redis
  redis: 
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data/:/data
      - ./redis/config/init/:/docker-entrypoint-initdb.d/